[package]
name = "xtended-numbers"
version = "2.2.1"
description = "Extended functionality for motoko number types, such as byte encoding"
repository = "https://github.com/edjCase/motoko_numbers"
keywords = [
  "numbers",
  "int",
  "integer",
  "nat",
  "float",
  "encode",
  "decode",
  "integer",
  "natural",
  "parse",
]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"buffer@0" = "0.1.0"

[dev-dependencies]
test = "2.1.1"
